### ISSUE TITLE
Opening Settigns crashes the app （設定を開くときにクラッシュする）

### ISSUE THREAD

**Issue by tinoue** [Precision-Marks/airsoft_spotter#2]
### Title

設定を開くときにクラッシュする

### Build Version

0.9.3

### Device Name (like Pixel8)

Kindle Fire HD 10 (9世代)

### Device OS

Android  9

### Component

Settings

### Severity

Critical

### Description

設定を開くと表示後すぐにクラッシュ

**Comment by precisionmarks** [comment]
デフォルト言語の読み上げ音声ファイルがインストールされてない場合に発生。

**Comment by precisionmarks** [comment]
fixed by 1.0.0
