### ISSUE TITLE
H.264 is preferred as the default video encoding format (ビデオのエンコーディングのデフォルトはH.264が望ましい)

### ISSUE THREAD

**Issue by tinoue** [Precision-Marks/airsoft_spotter#3]
### Build Version

0.9.3

### Device Name (like Pixel8)

All devices

### Device OS

Unknown

### Component

Settings

### Severity

Critical

### Description

デフォルトのエンコーディングはH.265になっているが、X(Twitter)が対応しておらず共有時にエラーになる。

**Comment by precisionmarks** [comment]
fixed by 1.0.0

**Comment by precisionmarks** [comment]
Android X app can share H.265 videos.
