### ISSUE TITLE
ハイパス画面のベスト設定について

### ISSUE THREAD

**Issue by GrandMasterYou** [Precision-Marks/airsoft_spotter#6]
### Build Version

0.9.3

### Device Name (like Pixel8)

GALAXY S9+

### Device OS

Unknown

### Component

Settings

### Severity

High

### Description

マルイターゲット使用時のセンター赤丸はハイパス画面上でどれがベストなのか?
1.塗り潰す
2.エッジ検出のみで塗り潰さない
3.バイパス画面上で認識させなくても良い

当方で3つ検証した結果は次の通り
Q1.この状態では着弾点が白く表示され、着弾点も認識されるが、以降滑り落ちるBB弾を誤認識する。音声ではスコアーカウントされるが射撃数の時間表示がN/Aの為、トータルスコアーへの加算はされない。

Q2.この状態では赤丸センターから滑り落ちるBB弾の誤認識はない。射撃カウント、スコアーも良好。

Q3.この状態結果はQ2と全く同じ。だがハイパス画面に対してはエッジ検出されてないので矛盾が生じると考える。

結果、ベスト設定は「2」と思えるがアプリ製作者の意見を求める。

よろしくお願いします。

**Comment by precisionmarks** [comment]
カメラ画面の右側、上から2つ目の白黒表示において、BB弾および的の白い円以外は黒に表示されるのを期待しています。
中央赤丸のエッジは利用していないので、２もしくは３のどちらでも構いません。
